Interactive functionality
scribe-org/Scribe-Data pull request #268
Opened 2024-10-07 12:17 UTC by axif0

### Contributor checklist

- [X] This pull request is on a [separate branch](https://docs.github.com/en/get-started/quickstart/github-flow) and not the main branch

---

### Description
The [rich](https://github.com/Textualize/rich) library enhances CLI output with colorful tables and messages, while  [questionary](https://github.com/tmbo/questionary)  provides interactive prompts for user input.

![attempt 2](https://github.com/user-attachments/assets/1aac7428-eac1-4a60-b906-4e56494a2bb8)

### Related issue

- #203 
- #202
- #209

2024-10-07 12:20 UTC, axif0 commented
cc: @mhmohona, @andrewtavis if you don't like the interactive UI or if it is not user friendly for community, I can make another PR using  [asciimatics](https://github.com/peterbrittain/asciimatics) as @wkyoshida said.

2024-10-09 04:55 UTC, mhmohona requested changes
Great work @axif0! ✨

2024-10-09 04:55 UTC, mhmohona commented on src/scribe_data/cli/interactive.py
> +def start_interactive_mode():
Please add docstring here, as well as for other functions.

2024-10-09 10:01 UTC, andrewtavis commented
One question on this, @axif0: What's the support from the packages you're using to display options as a grid? I'm quite conscious right now that as soon as we start adding in the new languages that people are working on, that we won't be able to see all the options on the screen anymore without displaying a grid. Do you think this is an option for the current dependencies?

Also, don't we need dependencies added to the `requirements.txt` file?

2024-10-10 22:09 UTC, andrewtavis commented
Sorry the dependencies are there... Lots of PRs over the last few days. I'm going to start testing this and comparing it against the work to re-ask users for options that was done in #216 and #239. I'm assuming that the dependencies will do this, but we'll see :)

2024-10-11 00:04 UTC, andrewtavis approved these changes
Ok lots of changes went through in my commit, but overall this is great, @axif0 😊

- Exit wasn't working
- We can now rerun data type only
- Minor color/style fixes
- Copy fixes (I changed export to request so it doesn't sound like the data is in Scribe-Data)
- Overall control fixes
- Asking the user if they want to continue when they didn't select something as the message was above the options for me, and is definitely going to be there for everyone as the options expand

This really is so cool :) :)

2024-10-11 00:04 UTC, merged